import type { Metadata } from "next";
import {
  Sofia_Sans,
  Sofia_Sans_Condensed,
  Sofia_Sans_Extra_Condensed,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const sofia = Sofia_Sans({ subsets: ["latin"] });
const sofia_cond = Sofia_Sans_Condensed({ subsets: ["latin"] });
const sofia_extra_cond = Sofia_Sans_Extra_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Paul Rodriguez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100">
      <body className={sofia.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
