// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact: dynamic(() => import("./ContactForm")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  home_hero1: dynamic(() => import("./HomeHero1")),
  image_block: dynamic(() => import("./ImageBlock")),
  navigation_project_blog: dynamic(() => import("./NavigationProjectBlog")),
  other_skills: dynamic(() => import("./OtherSkills")),
  recent_content: dynamic(() => import("./RecentContent")),
  skills: dynamic(() => import("./Skills")),
  tech_list: dynamic(() => import("./TechList")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_block: dynamic(() => import("./TextBlock")),
};
